name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - test
      - prod
env:
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [main,dev, test, prod]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./GitActionTask.sln

      - name: Build
        run: dotnet build ./GitActionTask.sln --configuration Release

      - name: Publish
        run: dotnet publish ./GitActionTask.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ matrix.environment }}-git-action-task
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

  database:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Run database migrations
        run: dotnet ef database update
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
